# Generated by Django 6.1 on 2026-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorderitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_purchase_order_product'),
        ),
    ]
