# Generated by Django 6.1 on 2026-08-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorder_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse'),
        ),
    ]
