# Generated by Django 6.1 on 2026-09-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_purchaseorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
