# Generated by Django 6.1 on 2026-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchaseorderitem_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
