# Generated by Django 6.1 on 2026-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchaseordernumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
