# Generated by Django 6.1 on 2026-09-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchaseorderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderattachment',
            name='attachment_type',
            field=models.CharField(choices=[('supplier_quote', 'Supplier Quote'), ('order_confirmation', 'Order Confirmation'), ('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
